routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/home', [
    'as' => 'admin.dashboard',
    'uses' => function () {
        return view('home');
    }
]);


Route::resource('register','Auth\RegisterController');
Route::resource('premium','PremiumController');
Route::get('show','Auth\RegisterController@showuser')->name('register.show');
Route::get('profile','Homecontroller@profile')->name('profile');
Route::post('update/{id}','Homecontroller@update_profile')->name('update_profile');

Route::get('/home','HomeController@index')->name('home');
Route::resource('permission','Permissioncontroller');
Route::resource('investment','Investmentcontroller');
Route::resource('role','Rolecontroller');
Route::resource('loan','LoanPersonController');
Route::get('/loan/{file}','LoanPersonController@edit')->name('pdf');
// verification route 
Route::get('varification/{verification_token}', 'Auth\RegisterController@createpass')->name('verify');
//activation route
Route::post('success', 'Auth\RegisterController@activeuser')->name('success');

app/Loan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Loan extends Model
{
    protected $fillable =['full_name','address','email','mobile','document_collected','loaner_photo','guarantor_name',
    'guarantor_phone','guarantor_photo','guarantor_email','document','loan_amount','loan_due','last_loan_installment',
     'issue_date','approved_proof','approved_date','last_full_payment_date','approved_by','created_by','updated_by','status'   ];
    
     public function  journal()
     {
         return $this->belongsTo(Loan::class);
     }
    }

resources/views/Loan/create.blade.php
@extends('layouts.master')
@section('title', 'Create Loan')
@section('con')

    @include('layouts.error')
    @include('flash::message')
    <div class="box box-primary">
        <div class="box-header with-border"><h3 class="box-title"> <b>Create Loan</b> </h3></div>
        <div class="box-body">
            <form action="{{ route('loan.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="row">
                <div class="form-group col-md-4">
                    <label for="name" class="col-sm-5  control-label col-form-label">Full Name</label>
                    <div class="col-sm-7">
                        <input type="text" name="full_name" class="form-control" value="{{ old('full_name') }}" id="name" placeholder="Full Name">
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="address" class="col-sm-5  control-label col-form-label">Address</label>
                    <div class="col-sm-7">
                        <input type="text" name="address" class="form-control" value="{{ old('address') }}"  id="address" placeholder="Address">
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="email" class="col-sm-5  control-label col-form-label">Email</label>
                    <div class="col-sm-7">
                        <input type="text" name="email" class="form-control" value="{{ old('email') }}" id="email" placeholder="Email">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="mobile" class="col-sm-5  control-label col-form-label">Mobile</label>
                    <div class="col-sm-7">
                        <input type="text" name="mobile" value="{{ old('mobile') }}" class="form-control" id="mobile" placeholder="Mobile">
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="document_collected" class="col-sm-5  control-label col-form-label">Document Collected</label>
                    <div class="col-sm-7">
                        <input type="file" name="document_collected" value="{{ old('document_collected') }}" class="form-control" id="document_collected">
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="loaner_photo" class="col-sm-5  control-label col-form-label">Loaner Photo</label>
                    <div class="col-sm-7">
                        <input type="file" name="loaner_photo" value="{{ old('loaner_photo') }}" class="form-control" id="loaner_photo" >
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="guarantor_name" class="col-sm-5  control-label col-form-label">Guarantor Name</label>
                    <div class="col-sm-7">
                        <input type="text" name="guarantor_name" value="{{ old('guarantor_name') }}" class="form-control" id="guarantor_name" placeholder="Guarantor Name">
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="guarantor_phone" class="col-sm-5  control-label col-form-label">Guarantor Phone</label>
                    <div class="col-sm-7">
                        <input type="text" name="guarantor_phone" value="{{ old('guarantor_phone') }}" class="form-control" id="guarantor_phone" placeholder="Guarantor Phone">
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="guarantor_photo" class="col-sm-5  control-label col-form-label">Guarantor Photo</label>
                    <div class="col-sm-7">
                        <input type="file" name="guarantor_photo" value="{{ old('guarantor_photo') }}" class="form-control" id="guarantor_photo" >
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="guarantor_email" class="col-sm-5  control-label col-form-label">Guarantor Email</label>
                    <div class="col-sm-7">
                        <input type="text" name="guarantor_email" value="{{ old('guarantor_email') }}" class="form-control" id="guarantor_email" placeholder="Guarantor Email ">
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="document" class="col-sm-5  control-label col-form-label">document</label>
                    <div class="col-sm-7">
                        <input type="file" name="document" value="{{ old('document') }}" class="form-control" id="document">
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="loan_amount" class="col-sm-5  control-label col-form-label">Loan Amount</label>
                    <div class="col-sm-7">
                        <input type="text" name="loan_amount" value="{{ old('loan_amount') }}" class="form-control" id="loan_amount" placeholder="Loan Amount">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="loan_due" class="col-sm-5  control-label col-form-label">Loan Due</label>
                    <div class="col-sm-7">
                        <input type="text" name="loan_due"value="{{ old('loan_due') }}" class="form-control" id="loan_due" placeholder="Loan Due ">
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="last_loan_installment" class="col-sm-5  control-label col-form-label">Last Loan Installment</label>
                    <div class="col-sm-7">
                        <input type="text" name="last_loan_installment"value="{{ old('last_loan_installment') }}" class="form-control" id="last_loan_installment" placeholder="last loan installment ">
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="issue_date" class="col-sm-5  control-label col-form-label">Issue Date</label>
                    <div class="col-sm-7">
                        <input type="text" name="issue_date"value="{{ old('issue_date') }}" class="form-control" id="datepicker" placeholder="Issue Date">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="approved_by" class="col-sm-5  control-label col-form-label">Approved by</label>
                    <div class="col-sm-7">
                        <input type="hidden" name="approved_by"value="{{ old('approved_by') }}" class="form-control" id="approved_by" >
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="approved_date" class="col-sm-5  control-label col-form-label">Approved Date</label>
                    <div class="col-sm-7">
                        <input type="text" name="approved_date"value="{{ old('approved_date') }}" class="form-control" id="targetdate">
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="approved_proof" class="col-sm-5  control-label col-form-label">Approved Proof</label>
                    <div class="col-sm-7">
                        <input type="file" name="approved_proof"value="{{ old('approved_proof') }}" class="form-control" id="approved_proof" placeholder="approved_proof ">
                    </div>
                </div>
            </div>
            <div class="row">
            <div class="col-md-4">
                <label for="last_full_payment_date" class="col-sm-5  control-label col-form-label">Last Full Payment Date</label>
                <div class="col-sm-7">
                    <input type="text" name="last_full_payment_date"value="{{ old('last_full_payment_date') }}" class="form-control" id="lastdate">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4"></div>
        <div class="col-sm-6 ">
            <button type="submit" class="btn btn-primary col-sm-3 ">Create</button>
        </div>
    </div>
            
                


            </form>

        </div>
    </div>
@endsection

resources/views/Loan/edit.blade.php
@extends('layouts.master')
@section('title', 'Create Loan')
@section('con')

    @include('layouts.error')
    @include('flash::message')
    <div class="box box-primary">
        <div class="box-header with-border"><h3 class="box-title"> <b>Create Loan</b> </h3></div>
        <div class="box-body">
            <form action="{{ route('loan.update',$loans->id)}}" method="post" enctype="multipart/form-data">
                {{csrf_field()}}
                {{method_field('PATCH')}}
                <div class="row">
                <div class="form-group col-md-4">
                    <label for="name" class="col-sm-5  control-label col-form-label">Full Name</label>
                    <div class="col-sm-7">
                        <input type="text" name="full_name" class="form-control" value="{{$loans->full_name}}" id="name" placeholder="Full Name">
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="address" class="col-sm-5  control-label col-form-label">Address</label>
                    <div class="col-sm-7">
                        <input type="text" name="address" class="form-control" value="{{$loans->address}}"  id="address" placeholder="Address">
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="email" class="col-sm-5  control-label col-form-label">Email</label>
                    <div class="col-sm-7">
                        <input type="text" name="email" class="form-control" value="{{$loans->email}}" id="email" placeholder="Email">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="mobile" class="col-sm-5  control-label col-form-label">Mobile</label>
                    <div class="col-sm-7">
                        <input type="text" name="mobile" value="{{ $loans->mobile }}" class="form-control" id="mobile" placeholder="Mobile">
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="document_collected" class="col-sm-5  control-label col-form-label">Document Collected</label>
                    <div class="col-sm-7">
                            
                            
                        <input type="file" name="document_collected"  class="form-control" id="document_collected">
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="loaner_photo" class="col-sm-5  control-label col-form-label">Loaner Photo</label>
                    <div class="col-sm-7">
                        <img src="/images/{{ $loans->loaner_photo }}" width="100px" height="100px">
                        <input type="file" name="loaner_photo"  class="form-control" id="loaner_photo"  >
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="guarantor_name" class="col-sm-5  control-label col-form-label">Guarantor Name</label>
                    <div class="col-sm-7">
                        <input type="text" name="guarantor_name" value="{{$loans->guarantor_name}}" class="form-control" id="guarantor_name" placeholder="Guarantor Name">
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="guarantor_phone" class="col-sm-5  control-label col-form-label">Guarantor Phone</label>
                    <div class="col-sm-7">
                        <input type="text" name="guarantor_phone" value="{{$loans->guarantor_phone}}" class="form-control" id="guarantor_phone" placeholder="Guarantor Phone">
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="guarantor_photo" class="col-sm-5  control-label col-form-label">Guarantor Photo</label>
                    <div class="col-sm-7">
                            <img src="/images/{{ $loans->guarantor_photo }}" width="100px" height="100px">
                        <input type="file" name="guarantor_photo"  class="form-control" id="guarantor_photo" >
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="guarantor_email" class="col-sm-5  control-label col-form-label">Guarantor Email</label>
                    <div class="col-sm-7">
                        <input type="text" name="guarantor_email" value="{{$loans->guarantor_email}}" class="form-control" id="guarantor_email" placeholder="Guarantor Email ">
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="document" class="col-sm-5  control-label col-form-label">document</label>
                    <div class="col-sm-7">
                        <input type="file" name="document" value="{{$loans->document}}" class="form-control" id="document">
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="loan_amount" class="col-sm-5  control-label col-form-label">Loan Amount</label>
                    <div class="col-sm-7">
                        <input type="text" name="loan_amount" value="{{$loans->loan_amount}}" class="form-control" id="loan_amount" placeholder="Loan Amount">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="loan_due" class="col-sm-5  control-label col-form-label">Loan Due</label>
                    <div class="col-sm-7">
                        <input type="text" name="loan_due" value="{{$loans->loan_due}}"  class="form-control" id="loan_due" placeholder="Loan Due ">
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="last_loan_installment" class="col-sm-5  control-label col-form-label">Last Loan Installment</label>
                    <div class="col-sm-7">
                        <input type="text" name="last_loan_installment" value="{{$loans->last_loan_installment}}" class="form-control" id="last_loan_installment" placeholder="last loan installment ">
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="issue_date" class="col-sm-5  control-label col-form-label">Issue Date</label>
                    <div class="col-sm-7">
                        <input type="text" name="issue_date"  value="{{$loans->issue_date}}" class="form-control" id="datepicker" placeholder="Issue Date">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="approved_by" class="col-sm-5  control-label col-form-label">Approved by</label>
                    <div class="col-sm-7">
                        <input type="hidden" name="approved_by"  value="{{$loans->approved_by}}" class="form-control" id="approved_by" >
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="approved_date" class="col-sm-5  control-label col-form-label">Approved Date</label>
                    <div class="col-sm-7">
                        <input type="text" name="approved_date" value="{{$loans->approved_date}}" class="form-control" id="targetdate">
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="approved_proof" class="col-sm-5  control-label col-form-label">Approved Proof</label>
                    <div class="col-sm-7">
                        <input type="file" name="approved_proof" value="{{$loans->approved_proof}}" class="form-control" id="approved_proof" placeholder="approved_proof ">
                    </div>
                </div>
            </div>
            <div class="row">
            <div class="col-md-4">
                <label for="last_full_payment_date" class="col-sm-5  control-label col-form-label">Last Full Payment Date</label>
                <div class="col-sm-7">
                    <input type="text" name="last_full_payment_date" value="{{$loans->last_full_payment_date}}" class="form-control" id="lastdate">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4"></div>
        <div class="col-sm-6 ">
            <button type="submit" class="btn btn-primary col-sm-3 ">Update</button>
        </div>
    </div>
            
                


            </form>

        </div>
    </div>
@endsection

resources/views/Loan/index.blade.php
@extends('layouts.master')
@section('title', 'Members Loan ')
@section('con')

    @include('layouts.error')
    @include('flash::message')
    <br>
    <div class="box">
        <div class="box-header">
            <h3 class="box-title"><b>Loans</b> </h3>
            <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">

                </div>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
                <tr>
                    <th scope="col">No</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Email</th>
                    <th>Mobile</th>
                    <th>Loaner Photo</th>
                    <th>Loan Amount</th>
                    <th>Loan Due</th>
                    <th>Last loan installment</th>
                    <th>Last loan installment</th>
                    <th>Action</th>
                </tr>
                <tbody>
                        <?php $count = 1; ?>
                @forelse($loans as $loan)
                    <tr>                      
                        <th scope="row">{{ $count++ }}</th>
                        <td>{{ $loan->full_name }}</td>
                        <td>{{ $loan->address }}</td>
                        <td>{{ $loan->email }}</td>
                        <td>{{ $loan->mobile }}</td>
                        <td> <img src="/images/{{ $loan->loaner_photo }}" width="70px" height="70px" alt="LP" ></td>             
                        <td>{{ $loan->loan_amount}}</td>
                        <td>{{ $loan->loan_due}}</td>
                        <td>{{ $loan->last_loan_installment}}</td>
                        <td>{{ $loan->last_full_payment_date}}</td> 
                        <td>
                            <a class="btn btn-raised btn-primary btn-sm"
                               href="{{ route('loan.show',$loan->id) }}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                               <a class="btn btn-raised btn-primary btn-sm"
                               href="{{ route('loan.edit',$loan->id) }}"><i class="fa fa-edit" aria-hidden="true"></i></a>
                               <form action="{{route('loan.destroy',$loan->id)}}" id="delete-form-{{ $loan->id }}"
                                  method="post" style="display: none;">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                            </form>
                            <button onclick="if(confirm('Are you Sure, You went to delete this?')){
                                    event.preventDefault();
                                    document.getElementById('delete-form-{{ $loan->id }}').submit();
                                    }else{
                                    event.preventDefault();
                                    }" class="btn btn-raised btn-danger btn-sm"><i class="fa fa-trash"
                                                                                   aria-hidden="true"></i></button>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td>No Data</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/Loan/show.blade.php
@extends('layouts.master')
@section('title', 'Loan Details')
@section('con')

    @include('layouts.error')
    @include('flash::message')
    <div class="box box-primary">
        <div class="box-header with-border"><h3 class="box-title"> <b>Loan Details</b> </h3></div>
        <div class="box-body">
           
                <div class="row">
                <div class="form-group col-md-4">
                    <label for="name" class="col-sm-5  control-label col-form-label">Full Name</label>
                    <div class="col-sm-7">
                            <p class="col-sm-5 ">{{$loans->full_name}}</p>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="address" class="col-sm-5  control-label col-form-label">Address</label>
                    <div class="col-sm-7">
                            <p  class="col-sm-5 ">{{$loans->address}}</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="email" class="col-sm-5  control-label col-form-label">Email</label>
                    <div class="col-sm-7">
                            <p  class="col-sm-5 ">{{$loans->email}}</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="mobile" class="col-sm-5  control-label col-form-label">Mobile</label>
                    <div class="col-sm-7">
                            <p  class="col-sm-5 ">{{$loans->mobile}}</p>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="document_collected" class="col-sm-5  control-label col-form-label">Document Collected</label>
                    <div class="col-sm-7">
                            <a href="/files/{{ $loans->document_collected }}">{{ $loans->document_collected }}</a>                           
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="loaner_photo" class="col-sm-5  control-label col-form-label">Loaner Photo</label>
                    <div class="col-sm-7">
                        <img src="/images/{{ $loans->loaner_photo }}" width="100px" height="100px">
                        
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="guarantor_name" class="col-sm-5  control-label col-form-label">Guarantor Name</label>
                    <div class="col-sm-7">
                            <p  class="col-sm-5 ">{{$loans->guarantor_name}}</p>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="guarantor_phone" class="col-sm-5  control-label col-form-label">Guarantor Phone</label>
                    <div class="col-sm-7">
                         <p  class="col-sm-5 ">{{$loans->guarantor_phone}}</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="guarantor_photo" class="col-sm-5  control-label col-form-label">Guarantor Photo</label>
                    <div class="col-sm-7">
                         <img src="/images/{{ $loans->guarantor_photo }}" width="100px" height="100px">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="guarantor_email" class="col-sm-5  control-label col-form-label">Guarantor Email</label>
                    <div class="col-sm-7">
                        <p  class="col-sm-5 ">{{$loans->guarantor_email}}</p>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="document" class="col-sm-5  control-label col-form-label">document</label>
                    <div class="col-sm-7">
                            <a href="/files/{{ $loans->document }}">{{ $loans->document }}</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="loan_amount" class="col-sm-5  control-label col-form-label">Loan Amount</label>
                    <div class="col-sm-7">
                            <p  class="col-sm-5 ">{{$loans->loan_amount}}</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="loan_due" class="col-sm-5  control-label col-form-label">Loan Due</label>
                    <div class="col-sm-7">
                            <p  class="col-sm-5 ">{{$loans->loan_due}}</p>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="last_loan_installment" class="col-sm-5  control-label col-form-label">Last Loan Installment</label>
                    <div class="col-sm-7">
                            <p  class="col-sm-5 ">{{$loans->last_loan_installment}}</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="issue_date" class="col-sm-5  control-label col-form-label">Issue Date</label>
                    <div class="col-sm-7">
                            <p  class="col-sm-5 ">{{$loans->issue_date}}</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="approved_by" class="col-sm-5  control-label col-form-label">Approved by</label>
                    <div class="col-sm-7">
                            <p  class="col-sm-5 ">{{$loans->approved_by}}</p>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label for="approved_date" class="col-sm-5  control-label col-form-label">Approved Date</label>
                    <div class="col-sm-7">
                            <p  class="col-sm-5 ">{{$loans->approved_date}}</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="approved_proof" class="col-sm-5  control-label col-form-label">Approved Proof</label>
                    <div class="col-sm-7">
                            <a href="/files/{{ $loans->approved_proof }}">{{ $loans->approved_proof }}</a>
                    </div>
                </div>
            </div>
            <div class="row">
            <div class="col-md-4">
                <label for="last_full_payment_date" class="col-sm-5  control-label col-form-label">Last Full Payment Date</label>
                <div class="col-sm-7">
                        <p  class="col-sm-5 ">{{$loans->last_full_payment_date}}</p>
                </div>
            </div>
        </div>
        
</div>
</div>
@endsection