routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/home', [
    'as' => 'admin.dashboard',
    'uses' => function () {
        return view('home');
    }
]);


Route::resource('register','Auth\RegisterController');
Route::resource('premium','PremiumController');
Route::get('show','Auth\RegisterController@showuser')->name('register.show');
Route::get('profile','Homecontroller@profile')->name('profile');
Route::post('update/{id}','Homecontroller@update_profile')->name('update_profile');

Route::get('/home','HomeController@index')->name('home');
Route::resource('permission','Permissioncontroller');
Route::resource('investment','Investmentcontroller');
Route::resource('role','Rolecontroller');
Route::resource('loan','LoanPersonController');
Route::get('/loan/{file}','LoanPersonController@edit')->name('pdf');
// verification route 
Route::get('varification/{verification_token}', 'Auth\RegisterController@createpass')->name('verify');
//activation route
Route::post('success', 'Auth\RegisterController@activeuser')->name('success');

app/Investment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Investment extends Model
{
    protected $fillable =[
        'user_id','user_type','investment_type','monthly_payment','interest_type','percentage_rate','issue_date','target_date_to_collect',
        'payment_due','last_payment_installment','created_by','updated_by'

    ];
    
}

app/Http/Controllers/InvestmentController.php
<?php

namespace App\Http\Controllers;
use App\User;
use App\Investment;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class InvestmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $investments=Investment::all();
       return view('Investment.show',compact('investments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        return view('Investment.create',compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'member' => 'required',
            'user_type' => 'required',
            'investment_type' => 'required',
            'monthly_payment' => 'required',
            'interest_type' => 'required',
            'percentage_rate' => 'required',
            'issue_date' => 'required',
            'target_date_to_collect' => 'required',
            'payment_due' => 'required',
            'last_payment_installment' => 'required',
            
    ]);
        Investment::create([
        'user_id' => $request['member'],
        'user_type' => $request['user_type'],
        'investment_type' => $request['investment_type'],
        'monthly_payment' => $request['monthly_payment'],
        'interest_type' => $request['interest_type'],
        'percentage_rate' => $request['percentage_rate'],
        'issue_date' => date("Y-m-d ",strtotime($request['issue_date'])), 
        'target_date_to_collect' => date("Y-m-d",strtotime($request['target_date_to_collect'])),
        'payment_due' => $request['payment_due'],
        'last_payment_installment' => date("Y-m-d",strtotime($request['last_payment_installment'])),
        'created_by'=>Auth::user()->id,
        'updated_by'=>Auth::user()->id
        ]);
        flash('Created successfully')->important()->success();
        return redirect()->route('investment.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Investment  $investment
     * @return \Illuminate\Http\Response
     */
    public function show(Investment $investment)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Investment  $investment
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $investments=Investment::find($id);
        $users = User::get();
        return View('Investment.edit',compact(['investments','users']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Investment  $investment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,  $id)
    {
        $investments= Investment::find($id);
        $investments->user_id =$request['member'];
        $investments->user_type = $request['user_type'];
        $investments->investment_type =$request['investment_type'];
        $investments->monthly_payment = $request['monthly_payment'];
        $investments->interest_type = $request['interest_type'];
        $investments->percentage_rate =$request['percentage_rate'];
        $investments->issue_date =date("Y-m-d ",strtotime($request['issue_date'])); 
        $investments->target_date_to_collect =date("Y-m-d",strtotime($request['target_date_to_collect']));
        $investments-> payment_due =$request['payment_due'];
        $investments-> last_payment_installment =date("Y-m-d",strtotime($request['last_payment_installment']));
        $investments-> created_by=Auth::user()->id;
        $investments->updated_by=Auth::user()->id;
        $investments->save();
        flash(' Updated successfully')->important()->success();
        return redirect()->route('investment.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Investment  $investment
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       Investment::find($id)->delete();
       flash('Deleted successfully')->important()->success();
        return redirect()->route('investment.index');
    }
}

resources/views/Investment/create.blade.php
@extends('layouts.master')
@section('title', 'Investment')
@section('con')
    @include('layouts.error')
    @include('flash::message')
    <div class="box box-primary">
        <div class="box-header with-border"><h3 class="box-title"> <b>Investment</b> </h3></div>
        <div class="box-body">
            <form action="{{ route('investment.store')}}" method="post">
                @csrf
                <div class="form-group row">
                    <label for="name" class="col-sm-3 text-right control-label col-form-label">Members Name</label>
                    <div class="col-sm-3">
                        <select class="form-control" name="member">
                            @foreach($users as $user)
                                <option hidden disabled selected value> Select A Member</option>
                                <option value="{{$user->id}}">{{$user->first_name.' '.$user->last_name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="ut" class="col-sm-3 text-right control-label col-form-label">Users Type</label>
                    <div class="col-sm-3">
                        <select class="form-control" name="user_type">
                        <option hidden disabled selected value> Select User type</option>
                        <option value="member">Member</option>
                        <option value="others">Others</option>
                    </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="it" class="col-sm-3 text-right control-label col-form-label">Investment Type</label>
                    <div class="col-sm-3">
                        <input type="text" name="investment_type" class="form-control" id="it">
                    </div>
                </div>
                <div class="form-group row"> 
                    <label for="mp" class="col-sm-3 text-right control-label col-form-label">Monthly Payment</label>
                    <div class="col-sm-3">
                        <input type="text" name="monthly_payment" class="form-control" id="mp">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="int" class="col-sm-3 text-right control-label col-form-label">Interest Type</label>
                    <div class="col-sm-3">
                       <select class="form-control" name="interest_type">
                        <option hidden disabled selected value> Select Interest Type</option>
                        <option value="percentage">Percentage</option>
                        <option value="fixed">Fixed</option>
                    </select>
                    </div>
                </div>
                <div class="form-group row"> 
                    <label for="pr" class="col-sm-3 text-right control-label col-form-label">Percentage Rate</label>
                    <div class="col-sm-3">
                        <input type="text" name="percentage_rate" class="form-control" id="pr">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="datepicker" class="col-sm-3 text-right control-label col-form-label">Issue Date</label>
                    <div class="col-sm-3">
                        <input type="text" name="issue_date" class="form-control" id="datepicker">
                    </div>
                </div>
                <div class="form-group row"> 
                    <label for="targetdate" class="col-sm-3 text-right control-label col-form-label">Target Date To Collect</label>
                    <div class="col-sm-3">
                        <input type="text" name="target_date_to_collect" class="form-control" id="targetdate">
                    </div>
                </div>
                <div class="form-group row"> 
                    <label for="pd" class="col-sm-3 text-right control-label col-form-label">Payment Due</label>
                    <div class="col-sm-3">
                        <input type="text" name="payment_due" class="form-control" id="pd">
                    </div>
                </div>
                <div class="form-group row"> 
                    <label for="lastdate" class="col-sm-3 text-right control-label col-form-label">Last Payment Installment</label>
                    <div class="col-sm-3">
                        <input type="text" name="last_payment_installment" class="form-control" id="lastdate">
                    </div>
                </div>
                <div class="border-top">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
    @endsection

resources/views/Investment/edit.blade.php
@extends('layouts.master')
@section('title', 'Investment')
@section('con')
    @include('layouts.error')
    @include('flash::message')

    <div class="box box-primary">
        <div class="box-header with-border"><h3 class="box-title"> <b>Investment</b> </h3></div>
        <div class="box-body">
            <form action="{{ route('investment.update',$investments->id)}}" method="post">
                {{csrf_field()}}
                {{method_field('PUT')}}
                <div class="form-group row">
                    <label for="name" class="col-sm-3 text-right control-label col-form-label">Members Name</label>
                    <div class="col-sm-3">
                        <select class="form-control" name="member">
                            @foreach($users as $user)
                                <option  value="{{$user->id}}" @if ($investments->user_id == $user->id) selected @endif > {{ $user->first_name.' '.$user->last_name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="ut" class="col-sm-3 text-right control-label col-form-label">Users Type</label>
                    <div class="col-sm-3">
                        <select class="form-control" name="user_type">
                        <option hidden disabled selected value> Select User type</option>
                        <option value="member" @if ($investments->user_type == "member")selected="selected" @endif>Members</option>
                        <option value="others" @if ($investments->user_type == "others")selected="selected" @endif>Others</option>
                     
                    </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="it" class="col-sm-3 text-right control-label col-form-label">Investment Type</label>
                    <div class="col-sm-3">
                        <input type="text" name="investment_type" value="{{ $investments->investment_type }}" class="form-control" id="it">
                    </div>
                </div>
                <div class="form-group row"> 
                    <label for="mp" class="col-sm-3 text-right control-label col-form-label">Monthly Payment</label>
                    <div class="col-sm-3">
                        <input type="text" name="monthly_payment"  value="{{ $investments->monthly_payment }}" class="form-control" id="mp">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="int" class="col-sm-3 text-right control-label col-form-label">Interest Type</label>
                    <div class="col-sm-3">
                       <select class="form-control" name="interest_type">
                        <option value="percentage" @if ($investments->interest_type == "percentage")selected="selected" @endif>Percentage</option>
                        <option value="fixed" @if ($investments->interest_type == "fixed")selected="selected" @endif>Fixed</option>
                    </select>
                    </div>
                </div>
                <div class="form-group row"> 
                    <label for="pr" class="col-sm-3 text-right control-label col-form-label">Percentage Rate</label>
                    <div class="col-sm-3">
                        <input type="text" name="percentage_rate" value="{{ $investments->percentage_rate }}" class="form-control" id="pr">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="datepicker" class="col-sm-3 text-right control-label col-form-label">Issue Date</label>
                    <div class="col-sm-3">
                        <input type="text" name="issue_date" value="{{ $investments->issue_date }}" class="form-control" id="datepicker">
                    </div>
                </div>
                <div class="form-group row"> 
                    <label for="targetdate" class="col-sm-3 text-right control-label col-form-label">Target Date To Collect</label>
                    <div class="col-sm-3">
                        <input type="text" name="target_date_to_collect" value="{{ $investments->target_date_to_collect }}" class="form-control" id="targetdate">
                    </div>
                </div>
                <div class="form-group row"> 
                    <label for="pd" class="col-sm-3 text-right control-label col-form-label">Payment Due</label>
                    <div class="col-sm-3">
                        <input type="text" name="payment_due" value="{{ $investments->payment_due }}"  class="form-control" id="pd">
                    </div>
                </div>
                <div class="form-group row"> 
                    <label for="lastdate" class="col-sm-3 text-right control-label col-form-label">Last Payment Installment</label>
                    <div class="col-sm-3">
                        <input type="text" name="last_payment_installment" value="{{ $investments->last_payment_installment }}" class="form-control" id="lastdate">
                    </div>
                </div>
                <div class="border-top">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
    @endsection

resources/views/Investment/show.blade.php
@extends('layouts.master')
@section('title', 'Investments')
@section('con')
    @include('layouts.error')
    @include('flash::message')
    <br>
    <div class="box">
        <div class="box-header">
            <h3 class="box-title"><b>Investments</b> </h3>
        </div>

        <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
                <tr>
                    <th>User Id</th>
                    <th>User Type</th>
                    <th>Investment Type</th>
                    <th>Monthly Payment</th>
                    <th>Interest Type</th>
                    <th>Percentage Rate</th>
                    <th>Issue Date</th>
                    <th>Target Date To Collect</th>
                    <th>Payment Due</th>
                    <th>Last Payment Installment</th>
                    <th>Action</th>
                </tr>
                <tbody>
                @forelse($investments as $investment)
                    <tr>
                        <td>{{ $investment->user_id }}</td>
                        <td>{{ $investment->user_type }}</td>
                        <td>{{ $investment->investment_type }}</td>
                        <td>{{ $investment->monthly_payment }}</td>
                        <td>{{ $investment->interest_type}}</td>
                        <td>{{ $investment->percentage_rate}}</td>
                        <td>{{ $investment->issue_date}}</td>
                        <td>{{ $investment->target_date_to_collect}}</td>
                        <td>{{ $investment->payment_due}}</td>
                        <td>{{ $investment->last_payment_installment}}</td>
                        <td>
                            <a class="btn btn-raised btn-primary btn-sm"
                               href="{{ route('investment.edit',$investment->id) }}"><i class="fa fa-edit"
                                                                                  aria-hidden="true"></i></a>
                            <form action="{{route('investment.destroy',$investment->id)}}" id="delete-form-{{ $investment->id }}"
                                  method="post" style="display: none;">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                            </form>
                            <button onclick="if(confirm('Are you Sure, You went to delete this?')){
                                    event.preventDefault();
                                    document.getElementById('delete-form-{{ $investment->id }}').submit();
                                    }else{
                                    event.preventDefault();
                                    }" class="btn btn-raised btn-danger btn-sm"><i class="fa fa-trash"
                                                                                   aria-hidden="true"></i></button>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td>No Data</td>
                    </tr>
                @endforelse
                </tbody>

            </table>
        </div>
    </div>
@endsection