routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/home', [
    'as' => 'admin.dashboard',
    'uses' => function () {
        return view('home');
    }
]);


Route::resource('register','Auth\RegisterController');
Route::resource('premium','PremiumController');
Route::get('show','Auth\RegisterController@showuser')->name('register.show');
Route::get('profile','Homecontroller@profile')->name('profile');
Route::post('update/{id}','Homecontroller@update_profile')->name('update_profile');

Route::get('/home','HomeController@index')->name('home');
Route::resource('permission','Permissioncontroller');
Route::resource('investment','Investmentcontroller');
Route::resource('role','Rolecontroller');
Route::resource('loan','LoanPersonController');
Route::get('/loan/{file}','LoanPersonController@edit')->name('pdf');
// verification route 
Route::get('varification/{verification_token}', 'Auth\RegisterController@createpass')->name('verify');
//activation route
Route::post('success', 'Auth\RegisterController@activeuser')->name('success');

resources/views/layouts/partials/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016</strong> All rights
    reserved.
  </footer>

resources/views/layouts/partials/navbar.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>A</b>LT</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Admin</b>LTE</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        @if(Auth::user()->photo)
                        <img src={{ asset('images/' . Auth::user()->photo)}} class="user-image" alt="User Image">
                        @else
                        <img src={{ asset('images/default.jpg') }} class="user-image" alt="User Image">
                        @endif
                        <span class="hidden-xs"> welcome {{ Auth::user()->first_name }}</span>
                    </a>
                    <ul class="dropdown-menu">

                        <li class="user-header">
                             @if(Auth::user()->photo)
                            <img src={{ asset('images/' . Auth::user()->photo) }} class="img-circle" alt="User Image">
                            @else
                            <img src={{ asset('images/default.jpg') }} class="img-circle" alt="User Image">
                            @endif
                            <p>
                                Alexander Pierce - Web Developer
                                <small>Member since Nov. 2012</small>
                            </p>
                        </li>
                        <!-- Menu Body -->

                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href={{ route('profile',Auth::user()->id)}} class="btn btn-default
                                   btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('logout') }}" class="btn btn-default btn-flat""
                                onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/partials/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src={{ asset('dist/img/user2-160x160.jpg') }} class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>Alexander Pierce</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-laptop"></i>
                    <span>Member Registration</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href={{ route('register.create') }}><i class="fa fa-circle-o"></i> Registration</a></li>
                    <li><a href={{ route('register.show') }}><i class="fa fa-circle-o"></i> Registered Member</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Role</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href={{ route('role.create' ) }}><i class="fa fa-circle-o"></i> Create Role</a></li>
                    <li><a href={{ route('role.index' ) }}><i class="fa fa-circle-o"></i> All roles</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Permission</span>
                    <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href={{ route('permission.create' ) }}><i class="fa fa-circle-o"></i> Create Permission</a>
                    </li>
                    <li><a href={{ route('permission.index' ) }}><i class="fa fa-circle-o"></i> All permission</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Monthly Premium</span>
                    <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href={{ route('premium.create' ) }}><i class="fa fa-circle-o"></i>Monthly Premium</a></li>
                    <li><a href={{ route('premium.index' ) }}><i class="fa fa-circle-o"></i> All Monthly Premium</a>
                    </li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Investment</span>
                    <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href={{ route('investment.create' ) }}><i class="fa fa-circle-o"></i>Investment</a></li>
                    <li><a href={{ route('investment.index' ) }}><i class="fa fa-circle-o"></i> All Investment</a>
                    </li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Loan</span>
                    <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href={{ route('loan.create' ) }}><i class="fa fa-circle-o"></i>Create Loan</a></li>
                    <li><a href={{ route('loan.index' ) }}><i class="fa fa-circle-o"></i> All Loans</a>
                       
                    </li>
                </ul>
            </li>

    </section>
    <!-- /.sidebar -->
</aside>