routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/home', [
    'as' => 'admin.dashboard',
    'uses' => function () {
        return view('home');
    }
]);


Route::resource('register','Auth\RegisterController');
Route::resource('premium','PremiumController');
Route::get('show','Auth\RegisterController@showuser')->name('register.show');
Route::get('profile','Homecontroller@profile')->name('profile');
Route::post('update/{id}','Homecontroller@update_profile')->name('update_profile');

Route::get('/home','HomeController@index')->name('home');
Route::resource('permission','Permissioncontroller');
Route::resource('investment','Investmentcontroller');
Route::resource('role','Rolecontroller');
Route::resource('loan','LoanPersonController');
Route::get('/loan/{file}','LoanPersonController@edit')->name('pdf');
// verification route 
Route::get('varification/{verification_token}', 'Auth\RegisterController@createpass')->name('verify');
//activation route
Route::post('success', 'Auth\RegisterController@activeuser')->name('success');

resources/views/Monthlypremium/edit.blade.php
@extends('layouts.master')
@section('title', 'Registered User')
@section('con')
    @include('layouts.error')
    <div class="box box-primary">
        <div class="box-header with-border"><h3 class="box-title">Monthly Premium</h3></div>
        <div class="box-body">
            <form class="form-horizontal" action="{{ route('premium.update',$premiums->id)}}" method="post">

                {{csrf_field()}}
                {{method_field('PATCH')}}
                <div class="form-group row">
                    <label for="name" class="col-sm-3 text-right control-label col-form-label">Members Name</label>
                    <div class="col-sm-3">
                        <select class="form-control" name="member">
                            @foreach($users as $user)
                            <option  value="{{$user->id}}" @if ($premiums->member_id == $user->id) selected @endif > {{ $user->first_name.' '.$user->last_name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="month" class="col-sm-3 text-right control-label col-form-label">Month of Payment</label>
                    <div class="col-sm-6">
                        <div id="sla-data-range" class="mrp-container nav navbar-nav">
                            <span class="mrp-icon"><i class="fa fa-calendar"></i></span>
                            <div class="mrp-monthdisplay" name="mop">
                                <span class="mrp-lowerMonth" id="mrp">Jul 2018</span>
                                <span class="mrp-to"> to </span>
                                <span class="mrp-upperMonth">Aug 2014</span>
                            </div>

                            <input type="hidden" value="201408" id="mrp-upperDate"/>
                        </div>
                        <input type="hidden" id="mrp-lowerDate"/>

                    </div>
                </div>

                <div class="form-group row">
                    <label for="amount" class="col-sm-3 text-right control-label col-form-label">Amount</label>
                    <div class="col-sm-6">
                        <input type="number" name="amount" class="form-control" id="amount"
                               value="{{ $premiums->total_collected }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="fine" class="col-sm-3 text-right control-label col-form-label">Fine</label>
                    <div class="col-sm-6">
                        <input type="number" name="fine" class="form-control" id="fine" value="{{ $premiums->penalty }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="fine" class="col-sm-3 text-right control-label col-form-label">Date</label>
                    <div class="col-sm-6">
                        <div class="input-group date">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="datepicker" class="form-control pull-right" id="datepicker"
                                   value="{{ $premiums->payment_date }}">
                        </div>
                    </div>
                </div>
                <div class="border-top">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>

        </div>
    </div>



@endsection

resources/views/Monthlypremium/monthlypremium.blade.php
@extends('layouts.master')
@section('title','Registered User')
@section('con')
    @include('layouts.error')
    @include('flash::message')
    <div class="box box-primary">
        <div class="box-header with-border"><h3 class="box-title"> <b>Monthly Premium</b> </h3></div>
        <div class="box-body">
            <form class="form-horizontal" action="{{ route('premium.store') }}" method="post">
                {{csrf_field()}}
                <div class="form-group row">
                    <label for="name" class="col-sm-3 text-right control-label col-form-label">Members Name</label>
                    <div class="col-sm-3">
                        <select class="form-control" name="member">
                            @foreach($users as $user)
                                <option hidden disabled selected value> Select a member</option>
                                <option value="{{$user->id}}">{{$user->first_name.' '.$user->last_name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="month" class="col-sm-3 text-right control-label col-form-label">Month of Payment</label>
                    <div class="col-sm-6">
                        <div id="sla-data-range" class="mrp-container nav navbar-nav">
                            <span class="mrp-icon"><i class="fa fa-calendar"></i></span>
                            <div class="mrp-monthdisplay" name="mop">
                                <span class="mrp-lowerMonth" id="mrp">Jul 2018</span>
                                <span class="mrp-to"> to </span>
                                <span class="mrp-upperMonth">Aug 2014</span>
                            </div>

                            
                        </div>
                        <input type="text"  id="mrp-upperDate"/>
                        <input type="text" id="mrp-lowerDate"/>

                    </div>
                </div>

                <div class="form-group row">
                    <label for="amount" class="col-sm-3 text-right control-label col-form-label">Amount</label>
                    <div class="col-sm-6">
                        <input type="number" name="amount" class="form-control" id="amount">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="fine" class="col-sm-3 text-right control-label col-form-label">Fine</label>
                    <div class="col-sm-6">
                        <input type="number" name="fine" class="form-control" id="fine">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="fine" class="col-sm-3 text-right control-label col-form-label">Date</label>
                    <div class="col-sm-6">
                        <div class="input-group date">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="datepicker" class="form-control pull-right" id="datepicker">
                        </div>
                    </div>
                </div>
                <div class="border-top">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>

        </div>
    </div>



@endsection

resources/views/Monthlypremium/show.blade.php
@extends('layouts.master')
@section('title', 'Registered User')
@section('con')

    @include('layouts.error')
    @include('flash::message')
    <br>
    <div class="box">
        <div class="box-header">
            <h3 class="box-title"><b>Monthly Premiums</b> </h3>
            <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">

                </div>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
                <tr>
                    <th>Id</th>
                    <th>Month of Payment</th>
                    <th>Amount</th>
                    <th>Fine</th>
                    <th>payment Date</th>
                    <th>Action</th>
                </tr>
                <tbody>
                @forelse($premiums as $premium)
                    <tr>
                        <td>{{ $premium->member_id }}</td>
                        <td>{{ $premium->month_of_payment }}</td>
                        <td>{{ $premium->total_collected }}</td>
                        <td>{{ $premium->penalty }}</td>
                        <td>{{ $premium->payment_date}}</td>
                        <td>
                            <a class="btn btn-raised btn-primary btn-sm"
                               href="{{ route('premium.edit',$premium->id) }}"><i class="fa fa-edit"
                                                                                  aria-hidden="true"></i></a>
                            <form action="{{route('premium.destroy',$premium->id)}}" id="delete-form-{{ $premium->id }}"
                                  method="post" style="display: none;">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                            </form>
                            <button onclick="if(confirm('Are you Sure, You went to delete this?')){
                                    event.preventDefault();
                                    document.getElementById('delete-form-{{ $premium->id }}').submit();
                                    }else{
                                    event.preventDefault();
                                    }" class="btn btn-raised btn-danger btn-sm"><i class="fa fa-trash"
                                                                                   aria-hidden="true"></i></button>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td>No Data</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
@endsection